### ISSUE TITLE
Manifest build fails

### ISSUE THREAD

**Issue by SuperQ** [prometheus/busybox#25]
The docker manifest creation fails in circleci.

```console
make manifest SUFFIX=
make: git: Command not found
# Manifest for "ulibc"
DOCKER_CLI_EXPERIMENTAL=enabled docker manifest create -a "quay.io/prometheus/busybox:uclibc" \
	"quay.io/prometheus/busybox-linux-amd64:uclibc" \
	"quay.io/prometheus/busybox-linux-armv7:uclibc" \
	"quay.io/prometheus/busybox-linux-armv8:uclibc"
unsupported manifest media type and no default available: application/vnd.docker.distribution.manifest.v1+prettyjws
make: *** [Makefile:37: manifest] Error 1
Exited with code 2
```

**Comment by johanneswuerbach** [comment]
Looks like quay doesn’t support manifests https://github.com/moby/buildkit/issues/409#issuecomment-394757219 :-( this sounds like a blocker as we otherwise can’t keep „quay.io/prometheus/prometheus“ working as the idea was to push the amd64 image to „quay.io/prometheus-linux-amd64“ and only add manifests for the main one :-(

We could probably also push „a real“ image to prometheus/prometheus only for quay, but that kind of if/else is what we actually wanted to avoid :-(

**Comment by SuperQ** [comment]
Ahh, makes sense. That's no good.

I guess we'll have to have a manifest/real image flag until quay supports manifests.

**Comment by simonpasquier** [comment]
I've pinged the Quay team internally and they might be able to fix it soon for https://quay.io/organization/prometheus. I'll keep you posted.

**Comment by simonpasquier** [comment]
I've been told that our organization has been upgraded and I've re-run the CI but the Makefile has a few typos (see #26).
